export { default as Load } from "./modules/Load";
export { default as Scroll } from "./modules/Scroll";
export { default as Nav } from "./modules/Nav";
export { default as Slider } from "./modules/Slider";
export { default as Split } from "./modules/Split";
export { default as Sound } from "./modules/Sound";
export { default as Modal } from "./modules/Modal";
export { default as ScrollTo } from "./modules/ScrollTo";
export { default as Update } from "./modules/Update";
